title: eMerge Property Solutions
email: info@emergepropertysolutions.com
description: >-
  eMerge Property Solutions provides an innovative approach to mitigating risk for our clients through big data analytics and progressive solutions.  We empower our employees and vendors by providing them with cutting edge automated capabilities and a knowledge base to create the perfect mix of tomorrow’s technology with today’s experience.
baseurl: ""
url: "http://emergepropertysolutions.com"
twitter_username: emergepropsol
linkedin_username: eMergepropertysolutions

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  team:
    output: false
  news:
    output: true
    permalink: /news/:title
    paginate: 6
    paginate_path: "/news/page:num/"
