title: eMerge Property Solutions
email: info@emergepropertysolutions.com
description: >-
  eMerge Property Solutions provides an innovative approach to mitigating risk for our clients through big data analytics and progressive solutions.  We empower our employees and vendors by providing them with cutting edge automated capabilities and a knowledge base to create the perfect mix of tomorrow’s technology with today’s experience.
baseurl: ""
url: "http://emergepropertysolutions.com"
twitter_username: emergepropsol
linkedin_username: emergepropertysolutions

# Build settings
exclude: 
  - _lib
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
timezone: America/Chicago
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Collections
collections:
  team:
    output: false
  news:
    output: true
    permalink: /news/:title/

pagination:
  enabled: true
  debug: false
  trail:
    before: 2
    after: 2

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: news
      excerpt_separator: <!--more-->
